const actionTypes = {
    SET_CURRENT_USER: "SET_CURRENT_USER",
    TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
    ADD_ITEM: "ADD_ITEM",
    DELETE_ITEM_FROM_CART: "DELETE_ITEM_FROM_CART",
    REMOVE_ITEM: "REMOVE_ITEM"
}

export default actionTypes